# ****************************
# config version 1.0 - 666pyke
#
# You can change the 'permission' parameter to whatever you want and provide the respective
# permission to the rank to which you want to associate the respective messages. If you want only
# special ranks, such as donors and staff members, to have special messages, don't give players
# permission from the 'DEFAULT' category. I hope you won't encounter any issues using my plugin.
#
# ****************************
donator:
  join-message: "%user% joined the server"
  leave-message: "%user% left the server"
  permission: joinmessages.donator

staff:
  join-message: "%user% joined the server"
  leave-message: "%user% left the server"
  permission: joinmessages.staff

default:
  join-message: "%user% joined the server"
  leave-message: "%user% left the server"
  permission: joinmessages.default

options:
  disable-vanilla-message: true # the default yellow messages such as "mareleepyke joined the game"

# priority for checking permissions will be staff > donator > default

messages:
  reloaded: "Plugin reloaded."